language: elixir

elixir: '1.7.0'
otp_release: '21.0'

script:
  - mix docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: doc
  on:
    branch: master
